[Interface]
Address = 172.31.0.2/24
SaveConfig = true
PostUp = wg set %i private-key /etc/wireguard/privatekey
PostUp = iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -o wlan0 -j MASQUERADE

[Peer]
PublicKey = ${WG_SERVER_PUBKEY}
AllowedIPs = 172.31.0.1/32
Endpoint =${ WG_SERVER_URL}:${WG_SERVER_PORT}
PersistentKeepalive = 25
